---
title: "Curriculum Vitae"
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%B %Y')`"
output: pdf_document
github: embruna
twitter: BrunaLab
phone: "(352) 514-3935"
email: embruna@ufl.edu
geometry: margin=1in
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
fontawesome: yes
bibliography: ./emb_cv_modular/EMB_publications.bib
csl: brunacv.csl
updated: yes
header-includes:
- \usepackage{etaremune}
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyfoot[R]{`r format(Sys.time(), '%B %Y')`}
- \fancyhead[R]{Emilio M. Bruna, p. \thepage}
- \usepackage{setspace}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \usepackage{sectsty} \subsubsectionfont{\color{darkmidnightblue}}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
- \usepackage{xhfill}
web: www.BrunaLab.org
---


```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
# library(citr)
library(RefManageR)

```

<!-- this next line suppresses the header (line, name,  page number) on 1st page -->
<!-- \begin{document}. -->
\thispagestyle{empty}  
# EMILIO MIGUEL BRUNA
\vspace{-0.3cm}  <!--space between name and address -->
University of Florida\hfill embruna@ufl.edu  
Dept. of Wildlife Ecology & Conservation &\hfill +1 (352) 846-0634  
Center for Latin American Studies\hfill&nbsp;[www.brunalab.org](www.brunalab.org)  
Gainesville, FL 32611-0430 USA\hfill&nbsp;
\vspace{-0.5cm}  <!--there was too much space, so reduced it with minus: -Xcm -->
<!-- ___   -->
<!-- \par\noindent\rule{\textwidth}{0.4pt} -->
\vspace{0.2cm}  
<!-- \textbf{\textcolor{darkmidnightblue}{RESEARCH \& TEACHING INTERESTS:}} Tropical ecology and conservation, plant population ecology, plant-animal interactions, scientometrics and bibliometrics, science & science policy in Latin America   -->

<!-- text size: https://www.overleaf.com/learn/latex/Font_sizes%2C_families%2C_and_styles -->
<!-- xrfill adjusts line position and width -->


### EDUCATION
<!--to indent a block of stuff treat it as a 'group' and then set leftskip -->
<!--be sure to indicate where the group ends with \endgroup -->

\begingroup 
\setlength{\leftskip}{.2cm} 

<!-- ### EDUCATION \hrulefill\ -->
<!-- TEXT \hrulefill\ -->
<!-- Here is some text\xfill{1pt} \par -->
<!-- Here is some text\xfill{8pt} \par -->
<!-- Here is some text\xhrulefill{darkmidnightblue}{2pt}\par -->
<!-- Here is some text\xhrulefill{darkmidnightblue}{1ex}\par -->
<!-- HOW TO MAKE LINE COLOR SAME'? -->
<!-- https://tex.stackexchange.com/questions/32597/vertically-centered-horizontal-rule-filling-the-rest-of-a-line -->
<!-- \textbf{\textcolor{darkmidnightblue}{EDUCATION }}\xrfill[0.5ex]{0.5pt} -->

<!-- ### EDUCATION \hrulefill -->



2001\hspace{4mm} Ph.D. in Population Biology, University of California, Davis  
<!-- &nbsp;&nbsp;&nbsp;&nbsp;\hspace{6mm}  _Dissertation Co-Advisors: Susan P. Harrison and Sharon Y. Strauss_   -->
1995\hspace{4mm} M.S. in Biology, University of California, San Diego  
<!-- &nbsp;&nbsp;&nbsp;&nbsp;\hspace{6mm} _Thesis Advisor: Ted J. Case_   -->
1994\hspace{4mm} B.S. in Ecology, Behavior, & Evolution with a minor in Literature, University of California, San Diego  

\endgroup 

<!-- ```{r ed, echo=FALSE,message = FALSE,warning=FALSE} -->

<!-- ed<-read_csv("./cv_files/education.csv") %>% -->
<!-- replace_na(list(program=" ", school=" ",year=" ",degree=" ")) -->
<!-- ed$program<-gsub('","',", ",ed$program) -->
<!-- ed$school<-gsub('","',", ",ed$school) -->
<!-- kbl(ed, -->
<!--     digits = 1, -->
<!--     format = "latex", -->
<!--     align="l", -->
<!--     col.names = NULL, -->
<!--     longtable = T, -->
<!--     row.names = FALSE, -->
<!--     booktabs=T, -->
<!--     linesep = "") %>% -->

<!--   kable_styling(bootstrap_options = c("hover"), -->
<!--                 latex_options = c("scale_down"), -->
<!--                 full_width = F, -->
<!--                 font_size = 10, -->
<!--                 position = "left") %>% -->
<!--   # row_spec(0:0, bold = T) %>% -->
<!--   # # column_spec(2, width = "35em") %>% -->
<!--   sub("\\\\toprule", "", .) %>% -->
<!--   sub("\\\\bottomrule", "", .) -->
<!-- ``` -->

### PROFESSIONAL APPOINTMENTS
\begingroup 
\setlength{\leftskip}{.2cm} 

2013-Present\hspace{6mm}**Professor & Distinguished Teaching Scholar**, University of Florida  
&nbsp;\hspace{24mm}Department of Wildlife Ecology & Conservation & Center for Latin American Studies  

2022-2025\hspace{10mm}**Secretary**, Ecological Society of America  

2020-2021\hspace{10mm}**President**, Association for Tropical Biology & Conservation  

2012-2021\hspace{10mm}**Director**, Florida-Brazil Linkage Institute, University of Florida
<!-- &nbsp;\hspace{24mm}Center for Latin American Studies, University of Florida   -->

2013-2019\hspace{10mm}**Editor-in-Chief**, _Biotropica_  

2014-2020\hspace{10mm}**Board of Directors**, Dryad Digital Data Repository  

2001-2002\hspace{10mm}**NSF Minority Postdoctoral Fellow**, Biological Dynamics of Forest Fragments Project  
&nbsp;\hspace{24mm}Instituto Nacional de Pesquisas da Amazônia-Smithsonian Institution  

\endgroup
<!-- ```{r positions, echo=FALSE,message = FALSE,warning=FALSE} -->

<!-- positions<-read_csv("./cv_files/positions.csv") %>% -->
<!-- replace_na(list(dates=" ", position=" ")) -->

<!-- # positions<-as.data.frame(positions) -->
<!-- # positions[1,1] <- cell_spec(positions[1, 1], "latex", bold = T)  -->
<!-- kbl(positions, -->
<!--     digits = 1, -->
<!--     format = "latex", -->
<!--     align="l", -->
<!--     col.names = NULL, -->
<!--     longtable = T, -->
<!--     row.names = FALSE, -->
<!--     booktabs=T, -->
<!--     linesep = "") %>% -->

<!--   kable_styling(bootstrap_options = c("hover"), -->
<!--                 latex_options = c("scale_down"), -->
<!--                 full_width = F, -->
<!--                 font_size = 10, -->
<!--                 position = "left") %>% -->
<!--   # row_spec(0:0, bold = T) %>% -->
<!--   # # column_spec(2, width = "35em") %>% -->
<!--   sub("\\\\toprule", "", .) %>% -->
<!--   sub("\\\\bottomrule", "", .) -->
<!-- ``` -->

\vspace{-0.2cm}
### SELECT AWARDS & FELLOWSHIPS

\begingroup 
\setlength{\leftskip}{.2cm} 
2022\hspace{4mm}Fellow, American Association for the Advancement of Science   
2014\hspace{4mm}Academy of Distinguished Teaching Scholars, University of Florida  
2012\hspace{4mm}Outstanding Paper Award, US Chapter of the International Association for Landscape Ecology  
2011\hspace{4mm}Graduate Advisor & Teacher of the Year, UF College of Agricultural & Life Sciences  
2009\hspace{4mm}University of Florida Research Foundation Professor  
2009\hspace{4mm}Fulbright Scholar, Brazil  
2007\hspace{4mm}Julie S. Denslow Outstanding Article in _Biotropica_ Prize, Association for Tropical Biology & Conservation  
2005\hspace{4mm}UF International Educator of the Year (untenured faculty category)  
<!-- &nbsp;\quad\quad\quad\quad _for the year's outstanding contribution to the field, published in any journal_   -->
<!-- &nbsp;\quad\quad\quad\quad _for the outstanding paper published in the journal Biotropica_   -->
<!-- &nbsp;\quad\quad\quad\quad _for the outstanding paper by a young investigator in the Journal of Ecology_ -->

\endgroup

## RELEVANT GRANTS IN SUPPORT OF RESEARCH & TRAINING (of >$5.5 million)  

\begingroup 
\setlength{\leftskip}{.2cm}  

1. National Science Foundation. "OPUS: Is habitat fragmentation detrimental or beneficial? Promoting our understanding of a contentious ecological question via synthesis." ($245,385, PI: E. M. Bruna)  

1. Maxwell-Hanrahan Foundation. _"Support for the UF TCD Seed Grant Program"_ ($10,000; PIs B. Loiselle, E. M. Bruna: $10,000 for 2022-2023, renewed 2023-2026 for $45,000)

1. National Science Foundation. _"SG: Synergistic effects of forest fragmentation and droughts on tropical plant population dynamics"_ ($199,904; PI: E. M. Bruna, Co-PIs: M. Uriarte, 2020-2022).

1. National Science Foundation. _"REU Supplement for SG: Synergistic effects of forest fragmentation and droughts on tropical plant population dynamics"_ ($14,400; PI: E. M. Bruna, Co-PIs: M. Uriarte, 2021).

1. National Science Foundation. _"The role of the matrix in fragmented landscapes: experimental tests and novel theory"_ ($548,058; PI: R. Fletcher, Co-PIs: E. M. Bruna, R. D. Holt, and B. Reichert, 2018-2023)  

\endgroup


## TEN PUBLICATIONS or PRODUCTS RELEVANT TO THE PROPOSAL (of N = 123)

\begingroup 
\setlength{\leftskip}{.2cm}  

**_Note regarding coauthorship on publications by lab members:_** _I am not necessarily a coauthor on all papers by lab members, including publications thesis chapters, as I consider mentorship regarding study development and design, analyses, and manuscript preparation fundamental to my role as their advisor._ 

1. D. S. Mason, K. M. Robertson, P. G. Hahn, E. M. Bruna, J. L. Willis, and M. A. Lashley. 2026. Fire promotes passive directed seed dispersal by birds. \textit{\textbf{Current Biology}} 36(1):28–37. https://doi.org/10.1016/j.cub.2025.11.014

1. Bruna, E. M., M. Uriarte, M. Rosa Darrigo, P. Rubim, C. F. Jurinitz, E. R. Scott, O. Ferreira da Silva, & W. John Kress. 2023. Demography of the understory herb _Heliconia acuminata_ (Heliconiaceae) in an experimentally fragmented tropical landscape. **_Ecology_** 104(12): https://e4174 doi.org/10.1002/ecy.4174 

1. Fletcher, R. J., T. A. H. Smith, N. Kortessis, E. M. Bruna, and R. D. Holt. 2023. Landscape experiments unlock the multi-scale relationships among habitat loss, fragmentation, and patch-size effects. **_Ecology_** 104(5): e4037. https://doi.org/10.1002/ecy.4037

1. 	Scott, E. R., M. Uriarte, and E. M. Bruna. 2022. Delayed effects of climate on vital rates lead to demographic divergence in Amazonian forest fragments. **_Global Change Biology_** 28(2):463-479. https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15900 **_Recipient of the Postdoctoral Excellence Award from the Ecological Society of America's Plant Population Ecology Section_**

1. Beckman, NG, CE Aslan, HS Rogers, O Kogan, JL Bronstein, JM Bullock, F Hartig, J HilleRisLambers, Y Zhou, D Zurell, JF Brodie, EM Bruna, RS Cantrell, RR Decker, E Efiom, EC Fricke, K Gurski, A Hastings, JS Johnson, BA Loiselle, MN Miriti, MG Neubert, L Pejchar, JR Poulsen, G Pufal, OH Razafindratsima, ME Sandor, K Shea, S Schreiber, EW Schupp, RS Snell, C Strickland, and J Zambrano. 2020. Advancing an interdisciplinary framework to study seed dispersal ecology. **_AoB Plants_** 12:plz048.  

1. Costa, AN, HL Vasconcelos, and EM Bruna. 2017. Biotic drivers of seedling establishment in Neotropical savannas: Selective granivory and seedling herbivory by leaf-cutter ants as an ecological filter. **_Journal of Ecology_** 105:132-141. [Ph. D. Thesis Chapter].    

1. Lucas, CM, EM Bruna, and CMN Nascimento. 2013. Seedling co-tolerance of multiple stressors in a disturbed tropical floodplain forest. **_Ecosphere_** 4(1):3.  [Ph. D. Thesis Chapter].  

1. Ferreira, AV, EM Bruna, and HL Vasconcelos. 2011. Seed predators limit plant recruitment in Neotropical savannas. **_Oikos_** 120:1013-1022.  

1. Uriarte, M. Anciães, M. T.B. da Silva, P. Rubim, E. Johnson, and E. M. Bruna.  2011. Disentangling the drivers of reduced long-distance seed dispersal by birds in an experimentally fragmented  landscape.  **_Ecology_** 92(4): 924-93. **_2012 Outstanding Paper in Landscape Ecology, Int. Assoc. for Landscape Ecology - US Chapter_**.  

1. Iacona, GD, LK Kirkman, and EM Bruna. 2010. Effects of resource availability on seedling recruitment in a fire-maintained savanna. **_Oecologia_** 163:171-180.  [Ph. D. Thesis Chapter].  

\endgroup


## RELEVANT COURSE DEVELOPMENT & TEACHING EXPERIENCE

\begingroup 
\setlength{\leftskip}{.2cm}  

The Future of Rain Forests (Undergraduate, 2021-2023,2025)  
Data Collection & Management for Latin American Studies (Graduate, 2019-2024, 2026)  
Plant-Animal Interactions (Graduate, biannually 2004-2010)  
Fundraising for Tropical Conservation & Development (Graduate, 2013 and biannually 2016-2020)  
Scientific Publishing (Graduate, 2014-2015, 2017-2018)  

\endgroup

## EDITORIAL POSITIONS & SERVICE

\begingroup 
\setlength{\leftskip}{.2cm}  

**Editor-in-Chief**: _Biotropica_ (2013-2019; _>2400 decisions_)  
**Associate Editor:** _Biotropica_ (2010-2013)  
**Subject Editor:** _PLOS Ecosystems_ (2025-Present), _Biotropica_ (2007-2019), _Ecology_ (2008-2012), _Ecological Monographs_ (2008-2012), _Ecological Applications_ (2008-2012).
