### AWARDS

\begingroup 
\setlength{\leftskip}{.2cm}  
2020\hspace{4mm}Selected for Induction into Alpha Zeta (Faculty Affiliate, UF Chapter)    
2020\hspace{4mm}Roche Teaching Scholar, UF College of Agricultural and Life Sciences    
2016\hspace{4mm}Sigma Xi (Full Member, University of Florida Chapter)    
2014\hspace{4mm}Academy of Distinguished Teaching Scholars, University of Florida  
2012\hspace{4mm}Outstanding Paper Award, US Chapter of the International Association for Landscape Ecology  
2011\hspace{4mm}Graduate Advisor & Teacher of the Year, UF College of Agricultural and Life Sciences  
2009\hspace{4mm}University of Florida Research Foundation Professor  
2007\hspace{4mm}Julie S. Denslow Outstanding Article in _Biotropica_ Prize, Association for Tropical Biology & Conservation  
2005\hspace{4mm}UF International Educator of the Year (untenured faculty category)  
2003\hspace{4mm}Diversity Scholar, American Institute for Biological Sciences  
2002\hspace{4mm}John L. Harper Early Career Researcher Award, British Ecological Society  
1994\hspace{4mm}Ernest C. Mort Leadership Excellence Award, Revelle College, UC San Diego  
<!-- &nbsp;\quad\quad\quad\quad _for the year’s outstanding contribution to the field, published in any journal_   -->
<!-- &nbsp;\quad\quad\quad\quad _for the outstanding paper published in the journal Biotropica_   -->
<!-- &nbsp;\quad\quad\quad\quad _for the outstanding paper by a young investigator in the Journal of Ecology_ -->

\endgroup