### INTERVIEWS & MEDIA APPEARANCES  
\begingroup 
\setlength{\leftskip}{.2cm}

2021\hspace{4mm} Chronicle for Higher Education, The Florida Independent Alligator, Associated Press, Nightline (ABC)  
2020\hspace{4mm} Washington Post   
2019\hspace{4mm} USA Today, CBC News Network (Canada), The Atlantic, The Verge, MSNBC’s Velshi & Ruhle  
&nbsp;\hspace{10mm} WIRED Magazine (2), Mashable, BBC World Service (UK), The Miradas Podcast    
2018\hspace{4mm} Popular Science, Associated Press, National Geographic, Scholastic Classroom Magazines   
&nbsp;\hspace{10mm} Gainesville Sun, Mongabay.com  
2017\hspace{4mm} The Wire (India), Chemistry World, Nature, Gainesville Sun  
2016\hspace{4mm} Chronicle of Higher Education, DailyDot, Nature, Mongabay.com  
2014\hspace{4mm} NPR’s Morning Edition/Joe’s Big Idea, TV Acre (Rede Globo Rio Branco) Bom Dia Amazônia   
&nbsp;\hspace{10mm} TV Gazetta ‘Entrevista com Rogério Wenceslau’ (Rede Record Rio Branco), Estado de São Paulo  
&nbsp;\hspace{10mm} Nature.com, WUFT, Science/Science Insider, Howler Soccer Magazine’s Dummy Podcast  
2013\hspace{4mm} SciDevNet, WSLR Florida-Caribe Radio Show  
2006\hspace{4mm} The Scientist Magazine, Science Minority Scientists Network  
2005\hspace{4mm} Science’s Next Wave, Televisão Universitária, Uberlândia, Folha de São Paulo  
2004\hspace{4mm} Science Magazine’s Minority Scientists Network  
2002\hspace{4mm} NPR’s Weekend Edition Saturday, BBC World Service Radio 4, Austrian Public Television’s Modern Times. 

\endgroup