### PROFESSIONAL APPOINTMENTS
\begingroup 
\setlength{\leftskip}{.2cm} 

2013-Present\hspace{6mm}**Professor & Distinguished Teaching Scholar**, University of Florida  
&nbsp;\hspace{24mm}Department of Wildlife Ecology & Conservation & Center for Latin American Studies  

2020-2021\hspace{10mm}**President**, Association for Tropical Biology and Conservation  

2012-2021\hspace{10mm}**Director**, Florida-Brazil Linkage Institute, University of Florida   
&nbsp;\hspace{24mm}Center for Latin American Studies, University of Florida  

2013-2019\hspace{10mm}**Editor-in-Chief**, _Biotropica_  

2014-2020\hspace{10mm}**Board of Directors**, Dryad Digital Data Repository  

2005-Present\hspace{6mm}**Adjunct Professor**, Universidade Federal de Uberlândia, Brazil  
&nbsp;\hspace{24mm}Graduate Program in Ecology and Natural Resource Conservation  

2007-2013\hspace{10mm}**Associate Professor**, University of Florida  
&nbsp;\hspace{24mm}Department of Wildlife Ecology & Conservation & Center for Latin American Studies  

2002-2007\hspace{10mm}**Assistant Professor**, University of Florida    
&nbsp;\hspace{24mm}Department of Wildlife Ecology & Conservation & Center for Latin American Studies  

2001-2002\hspace{10mm}**NSF Minority Postdoctoral Fellow**, Biological Dynamics of Forest Fragments Project  
&nbsp;\hspace{24mm}Instituto Nacional de Pesquisas da Amazônia-Smithsonian Institution  

\endgroup