### SERVICE - OTHER INSTITUTIONS  
\begingroup 
\setlength{\leftskip}{.2cm}

Tenure and Promotion Portfolio Evaluations: 2021 (2), 2020 (3), 2018 (2), 2017 (1), 2016 (3), 2015 (1), 2011 (1)  
ASN/SSE/SSB Committee on Development a Professional Code of Ethics (2018-2019)  
External Advisor, 2nd Planning Workshop, Brazilian Biodiversity and Ecosystem Services Synthesis Center (2018)  
Discussant, Research & Writing Conference, Florida Education Fund/McKnight Doctoral Fellowship Program (2016)  
Co-host & Co-organizer, UC Davis Population Biology Workshop in Ecology (2000)  
Student Representative, UC Davis Population Biology GRT Executive Committee (1996-1997)  
UC San Diego EAP Selection Committee, Tropical Biology Program (1994)  

\endgroup 

### SERVICE - ASSOCIATION FOR TROPICAL BIOLOGY AND CONSERVATION  
\begingroup 
\setlength{\leftskip}{.2cm}

President (2021)  
President-Elect (2020)  
Program Committee, Annual Meeting of the ATBC (2021)    
Student Field Grants Selection Committee (2020)  
Student Field Grants Selection Committee (2020)  
Crowdfunding Workshop, Annual Meeting of the ATBC (2018)  
Annual Meeting Scientific Committee (2017, 2012)  
Councillor (2009-2011)  
Conservation Committee (2004-2006)  
Co-organizer, Symposium on Amazonian Conservation, Annual Meeting (2004)  

\endgroup 

### SERVICE AS A REVIEWER AND EDITOR  

\begingroup 
\setlength{\leftskip}{.2cm}

*__Biotropica:__* Editor-in-Chief (2013-2019), Associate Editor (2010-2013), Editorial Board (2007-2019)  

*__Ecology__*, *__Ecological Monographs__*, and *__Ecological Applications__*: Editorial Board (2008-2012)  

__*Ad hoc* referee for journals (No. of reviews):__ *Trends in Ecology and Evolution* (1), *Nature Human Behavior* (1), *Information, Communication,& Society* (1), *Ecology* (4), *Ecology and Evolution* (1),  *Methods in Ecology & Evolution* (1), *Conservation Biology* (5), *Biological Conservation* (7), *Ecological Applications* (1), *Oecologia* (4), *Journal of Tropical Ecology* (2), *Journal of Ecology* (6), *New Phytologist* (1), *American Naturalist* (3), *Plant Ecology* (3), *Proc. Roy. Soc. Lond. B* (1), *Journal of Applied Ecology* (1), *Biotropica* (12), *Ecography* (5), *Ciência y Cultura* (2), *Oikos* (1), *Revista Chilena de Historia Natural* (1), *Biochemical Systematics & Ecology* (1), *Ecology Letters* (2), *Insectes Sociaux* (1), *American J. of Botany* (1), *Scientometrics* (1), *F1000* (1), *Desenvolvimento e Meio Ambiente* (1), *PLoS Biology* (2), *PLoS ONE* (1), *Theoretical Ecology* (1), *Conservation Science & Practice* (1)

__US National Science Foundation:__ Proposal Review Panels: DEB Ecology (2005), DEB Population and Evolutionary Processes (2007), DEB Population and Community Ecology (2011, 2013). Ad-hoc proposal review: UMEB Program (2), RUI Program (1), Ecological Biology Program (3), AMERICAS Dissertation Improvement Grant (1), NSF Global Scientists and Engineers Program (1), Population and Evolutionary Processes Program (1), International Research Fellowship Program (1), Population and Community Ecology Program (2), Dimensions of Biodiversity Program (1)

__Other service as a reviewer (No. of reviews or year of service)__: *Red Line Editorial (2019, technical review of a K-12 book), Mindlin Foundation (2018), Cornell University Press (2017), Instituto Serrapliheira (2017), HHMI Professors Program (2017), UF FAES/CRIS Project Proposals (2), U. of Chicago Press (1), Alfred P. Sloan Foundation Minority Ph.D. Program (3). National Geographic Society (1), U. of California Press (1)  

\endgroup 