### SERVICE - UNIVERSITY OF FLORIDA  

\begingroup 
\setlength{\leftskip}{.2cm}
Samuel P. Harn Museum of Art Faculty Council (2012-2015)  
Selection Committee, UF International Educator of the Year Award (2006)  
Selection Committee, UF Teacher/Scholar of the Year (2015)  
UF Research Foundation Professorship Selection Committee (2010)  
Fulbright Fellows Campus Interview Committee  (2019)  
Catalyst Fellow, UF Innovation Academy Catalyst Challenge (2018)  
External Advisory Committee, Institute of Museum & Library Services Grant (2015-2018)  
International Outreach Advisory Council, Graduate School (2014-Present)  
Internal Advisory Board, Innovation through Institutional Integration (I3) program (2010-2014)  
Administrative Council, QSE3 IGERT (2008-2014)  
Peer Teaching Evaluation for Dr. Michelle Mack, UFL Department of Botany (2006)    

\endgroup 

### SERVICE - UF COLLEGE OF AGRICULTURAL AND LIFE SCIENCES  
\begingroup 
\setlength{\leftskip}{.2cm}

IFAS International Programs Advisory Team (2020-Present)  
UF-CALS Outstanding Thesis Selection Committee (2020)  
York Distinguished Lecture Selection Committee (2015)  
Search and Screen Committee, CALS Quantitative Sciences Faculty Positions (2013)  
Coordinating Committee, School for Natural Resources & the Environment (2012)  
Invited Speaker, College of Agricultural & Life Sciences Teaching Grantsmanship Workshop (2012)  
Mentorship Committee for Dr. Luke Flory, Dept. of Agronomy (2012)  
IFAS Faculty Professional Development Advisory Committee (2012-2013)  
Selection Committee, College of Agricultural & Life Sciences Teaching and Advising Awards (2012)  
Invited Speaker, College of Agriculture and Life Sciences Teaching Enhancement Symposium (2010)  
College of Agricultural & Life Sciences Undergraduate Scholarships & Awards Committee (2007-2009)  
Unifas Focus Group (Teaching Section), College of Agriculture and Life Sciences (2007)  
Unifas Advisory Committee, College of Agriculture and Life Sciences (2006-2007)  
Invited Speaker, College of Agriculture and Life Sciences Teaching Enhancement Symposium (2005)  
Commencement Marshal, College of Agricultural and Life Sciences (2004, 2014,2015, 2018)   
SNRE Seed Grant and New Faculty Support Grant Programs (2005)  

\endgroup 

### SERVICE - UF DEPARTMENT OF WILDLIFE ECOLOGY & CONSERVATION  

\begingroup 
\setlength{\leftskip}{.2cm}

Research Committee (2005-2007, 2020-present)  
Space Committee (2019)  
Communications Committee (2014-Present)  
Graduate Program Committee (2005-2012)  
International Programs Committee (2006-2010)  
Steering Committee, PSTC Compton Fellowship Program (2002-2010)  
Seminar Series Coordinator (2003-2004)  
Seminar Series Coordinator (2015)  
Chair, Pre-Tenure Mentorship Committee for Dr. Robert Fletcher (2009-2012)  
Search and Screen Committee, Research Asst. Professor, Zoo Wildlife Conservation Biology (2020)   
Search and Screen Committee, Asst. Professor of Population Ecology (2017)  
Search and Screen Committee, Department Head (2006)  
Search and Screen Committee, Asst. Professor of Landscape Ecology (2004)  
Search and Screen Committee, Asst. Professor of Conservation Genetics, WEC (2004)  
Chair, Peer Teaching Evaluation Committee for Dr. Ethan White (2019-2020)  
Chair, Peer Teaching Evaluation Committee for Dr. Morgan Ernest (2017-2018)  
Chair, Peer Teaching Evaluation Committee for Dr. Lyn Branch (2011)  
Chair, Peer Teaching Evaluation Committee for Dr. Bill Pine (2010)  
Chair, Peer Teaching Evaluation Committee for Dr. Robert Fletcher (2009)  
Tenure Mentorship Committee for Dr. Nia Morales (2021-2022)  
Peer Teaching Evaluation Committee for Dr. Madan Oli (2003)  
Peer Teaching Evaluation Committee for Dr. Bill Pine (2015)  

\endgroup 

### SERVICE - UF CENTER FOR LATIN AMERICAN STUDIES  
\begingroup 
\setlength{\leftskip}{.2cm}

LAS Faculty Advisory Council (2020-2023)  
LAS Bylaws Revision Committee (2020-2021)  
LAS Merit Evaluation Committee (2015-2017)  
LAS Graduate Admissions and Fellowship Committee (2007)  
Chair, Search and Screen Committee, Lecturer in Latin American Studies (2015)  
Chair, LAS Awards and Scholarship Committee (2019)  
Search and Screen Committee, LAS Communications Coordinator (2015)  
Bacardi Seminar Series Coordinator (Spring 2015)  
Academic Advisor, Tropical Conservation and Development (TCD) Program (2008-2011) 
Faculty Advisor, TCD Graduate Student Organization (2008-2016)  
Steering Committee, TCD Program (2002-2008, 2010-2016, 2018-present)  
Chair, TCD Fellowship Committee (2012)  
Chair, TCD Field Research Grants Committee (2004, 2008, 2009, 2010, 2015, 2020)  
Chair, Marianne Schmink Award Selection Committee (2010, 2011, 2013)  
TCD Field Research Grants Committee (2003, 2004)  
TCD Fellowship Committee (2003-2005)  
Organizing Committee, TCD Strategic Planning (2007-2008)  
Curriculum Committee, Master’s Program in Sustainable Development Practice (2010-2012)  
Advisory Council, Amazon Conservation Leadership Initiative (2004-2005)  
Advisory Committee, Pan-Amazon Community of Practice Project (2018-2020) 

\endgroup  
