### COURSE DEVELOPMENT & TEACHING EXPERIENCE

\begingroup 
\setlength{\leftskip}{.2cm} 

__Courses Taught at the University of Florida__  
Ecology and Conservation of Tropical Wildlife (Undergraduate, 03,05,07,11,12,14,18)  
Data Collection & Management for Latin American Studies (Graduate, 2019)  
Plant-Animal Interactions (Graduate, 2004, 2006, 2008, 2010)  
Fundraising for Tropical Conservation & Development (Graduate, 2013, 2016, 2018, 2020)  
Scientific Publishing (Graduate, 2014, 2015, 2017, 2018)  
Ecological Principles for Development & Conservation Professionals (Graduate, 2010, 2011, 2012)  
Tropical Forest Community Ecology (Graduate, 2000)  
Design and Methods of Research in Latin American Studies (Graduate, 2008, 2010)  
Research Methods in Tropical Conservation & Development (Graduate, 2003-2007)  
Seminar in Wildlife Ecology and Conservation (Graduate, 2003, 2004)  
Social Media Workshop (Graduate, 2016)  

__Other Teaching Experience__  


*__Guest Lectures in UF Courses__*  
Diverse Perspectives in Conservation(WIS4934, 2021)
Human Footprint on the Landscape (GEO3352, 2019)  
Facets of Sustainability (IDS2154, 2011, 2013)  
Environmental Planning & Design (EES 6051, 2016,2018)  
The Amazon (LAS6290, 2009, 2011)  
Design & Methods of Research in Latin American Studies (Graduate, 2019, 2020)  
Discovering Research & Communicating Science (IDH3931, 2015)  
Wildlife Techniques (WIS4945C, 2005)  
Development Theory & Practice (LAS6938, 2010)  
Wildlife Population Modeling (WIS6466, 2003, 2006, 2008, 2010)  
Principles of Wildlife Ecology & Conservation (WIS6934, 2008)  
Luso-Brazilian Civilization (POW3500, 2004)  

*__Courses Taught & Guest lectures at Other Institutions__*  
Univ. Federal de Uberlândia: Mechanisms of Species Coexistence (Graduate Course, 2006)  
Univ. Federal de Uberlândia: Data Management & Archiving (Graduate Course, 2012, 2014)  
Univ. Federal de Uberlândia: Scientific Publishing (Graduate Course, 2011)  
INPA: Population Ecology (Guest Lecturer 2002, 2003)  
INPA: Community Ecology (Guest Lecturer 2002)

*__Participation in Field Courses__*  
OTS 3M Field Course (2001)  
OTS Amazonian Ecosystems Field Course (2001)  
Antioch College Semester Abroad in Brazil (1999, 2001)  
Univ. Federal do Amazonas, Fragmented Landscapes Field Course (2000, 2002)  

\endgroup